// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/maps/windy-island.tsx";
import * as $$0 from "./islands/Footer.tsx";
import * as $$1 from "./islands/Tile.tsx";

const manifest = {
	routes: {
		"./routes/[name].tsx": $0,
		"./routes/api/joke.ts": $1,
		"./routes/index.tsx": $2,
		"./routes/maps/windy-island.tsx": $3,
	},
	islands: {
		"./islands/Footer.tsx": $$0,
		"./islands/Tile.tsx": $$1,
	},
	baseUrl: import.meta.url,
};

export default manifest;
